import { test, expect } from '@playwright/test';
async function login(page: import('@playwright/test').Page, member = false) {
  await page.goto('/');
  await page.getByRole('radio', { name: member ? 'Nihaal Team Member' : 'Harsha Owner / Admin' }).click();
  await page.getByLabel(/Account Password/).fill('test-only-password-123456');
  await page.getByRole('button', { name: /Enter HAN Workspace/ }).click();
  await expect(page.getByRole('heading', { name: member ? 'Welcome back, Nihaal.' : 'Welcome back, Harsha.' })).toBeVisible();
}
test('Lead details persist, outcome selection and search work after reload', async ({page}) => {
  await login(page);
  await page.getByRole('button', {name:'Growth',exact:true}).click();
  await page.getByRole('button', {name:'Manage leads'}).click();
  await page.getByRole('button', {name:'Add lead',exact:true}).click();
  await page.getByLabel('Lead name').fill('Verified business');
  await page.getByLabel('Email',{exact:true}).fill('client@example.com');
  await page.getByLabel('Phone',{exact:true}).fill('+91 9000000000');
  await page.getByLabel('Deal value (₹)').fill('5432.10');
  await page.getByLabel('Source',{exact:true}).fill('Referral');
  await page.getByLabel('Follow-up date').fill('2026-10-15');
  await page.getByLabel('Lead owner').selectOption('user-2');
  await page.getByLabel('Status',{exact:true}).selectOption('Won');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByText('Verified business',{exact:true})).toBeVisible();
  await page.reload();
  await page.getByRole('button', {name:'Growth',exact:true}).click();
  await page.getByRole('button', {name:'Manage leads'}).click();
  await page.getByRole('textbox',{name:'Search Leads'}).fill('Verified business');
  await expect(page.getByRole('combobox',{name:'Status for Verified business'})).toHaveValue('Won');
  await page.getByRole('button',{name:'Edit',exact:true}).click();
  await expect(page.getByLabel('Email',{exact:true})).toHaveValue('client@example.com');
  await expect(page.getByLabel('Deal value (₹)')).toHaveValue('5432.1');
  await expect(page.getByLabel('Lead owner')).toHaveValue('user-2');
  await expect(page.getByLabel('Follow-up date')).toHaveValue('2026-10-15');
  await page.getByRole('button',{name:'Close dialog'}).click();
});
test('Server validation preserves the form and never falsely queues a rejected save', async ({page}) => {
  await login(page);
  await page.getByRole('button',{name:'Money',exact:true}).click();
  await page.getByRole('button',{name:'Add expense',exact:true}).first().click();
  await page.getByLabel('Title',{exact:true}).fill('Rejected expense');
  await page.getByLabel('Amount (₹)').fill('10000000001');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByText(/The change was not saved/)).toBeVisible();
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('han_v2_queue_user-1') || '[]').length)).toBe(0);
});
test('Offline reload, queue sync and repeat reconnect preserve exactly one task', async ({page,context}) => {
  await login(page);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Welcome back, Harsha.'})).toBeVisible();
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Welcome back, Harsha.'})).toBeVisible();
  await page.getByRole('button',{name:'Work',exact:true}).click();
  await page.getByRole('button',{name:'View tasks'}).click();
  await page.getByRole('button',{name:'Add task',exact:true}).click();
  await page.getByLabel('Task title').fill('Offline unique task');
  await page.getByRole('button',{name:'Save',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button',{name:'You',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Pending changes (1)'})).toBeVisible();
  await context.setOffline(false);
  await expect(page.getByRole('heading',{name:'Pending changes (1)'})).toHaveCount(0,{timeout:10000});
  await context.setOffline(true); await context.setOffline(false);
  await page.getByRole('button',{name:'Work',exact:true}).click();
  await page.getByRole('button',{name:'View tasks'}).click();
  await page.getByRole('textbox',{name:'Search Tasks'}).fill('Offline unique task');
  await expect(page.getByText('Offline unique task',{exact:true})).toHaveCount(1);
});
test('Logout clears account cache and a member never sees owner-only cached projects', async ({page,context}) => {
  await login(page);
  await page.getByRole('button',{name:'You',exact:true}).click();
  await page.getByRole('button',{name:'Sign out / switch identity'}).click();
  await expect(page.getByRole('heading',{name:'Who are you?'})).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem('han_v2_cache_user-1'))).toBeNull();
  await login(page,true);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Welcome back, Nihaal.'})).toBeVisible();
  await context.setOffline(true); await page.reload();
  await expect(page.getByRole('heading',{name:'Welcome back, Nihaal.'})).toBeVisible();
  await page.getByRole('button',{name:'Work',exact:true}).click();
  await expect(page.getByText('Lalitha Birthday Website',{exact:true})).toHaveCount(0);
});
test('Radio keyboard controls, modal focus, overdue filter and desktop fit', async ({page}) => {
  await page.setViewportSize({width:1280,height:900});
  await page.goto('/');
  const owner = page.getByRole('radio',{name:'Harsha Owner / Admin'});
  await owner.focus(); await owner.press('ArrowDown');
  await expect(page.getByRole('radio',{name:'Nihaal Team Member'})).toBeFocused();
  await expect(page.getByRole('radio',{name:'Nihaal Team Member'})).toHaveAttribute('aria-checked','true');
  await login(page);
  await page.getByRole('button',{name:'Review',exact:true}).click();
  await expect(page.getByRole('button',{name:'Project: Reviewly, Progress: 0 percent'})).toBeVisible();
  await expect(page.getByRole('button',{name:/Project: AR Dish Preview/})).toHaveCount(0);
  await page.getByRole('button',{name:'Add project',exact:true}).click();
  await expect(page.getByLabel('Deadline (optional)')).toHaveValue('');
  await expect(page.getByRole('button',{name:'Close dialog'})).toBeFocused();
  await page.getByRole('button',{name:'Close dialog'}).press('Shift+Tab');
  await expect(page.getByRole('button',{name:'Save',exact:true})).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button',{name:'Add project',exact:true})).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
test('Notification read action disappears when all are read; no manual creation control', async ({page}) => {
  await login(page);
  await page.getByRole('button',{name:'Notifications',exact:true}).click();
  const read = page.getByRole('button',{name:/Mark all as read/});
  if (await read.count()) await read.click();
  await expect(read).toHaveCount(0);
  await expect(page.getByRole('button',{name:/Add notification/i})).toHaveCount(0);
});
